Python:
  - "(Python|PYTHON|python)"
C:
  - "(C)"
C++:
  - "(C++|c++)"
Java:
  - "(Java|JAVA)"
enhancement:
  - "(enhancement)"
bug:
  - "(bug|Bug|BUG)"  
Urgent:
  - "(urgent|URGENT|Urgent)"  
documentation:
  - "(documentation)"

